version: '3'
services:
  ollama-container:
    image: ollama/ollama
    volumes:
      - ./data/ollama:/root/.ollama
    ports:
      - 11434:11434
  streamlit-app:
    image: rajamarthala/ai-assitant-finnish:3b
    ports:
      - 8501:8501